### ISSUE TITLE
pain.001.001.09

### ISSUE THREAD

**Issue by patroqueeet** [sebastienrousseau/pain001#24]
dear, Swiss market will move to .09 version in 2025, do you have a quick hint, how to get this done with this very nice lib?

**Comment by sebastienrousseau** [comment]
@patroqueeet yes I need to develop it but if you are happy to help that will be great 😉

**Comment by sebastienrousseau** [comment]
@patroqueeet  Have a look at the latest release and let me know

**Comment by patroqueeet** [comment]
ps: was searching the net today for a pain.001.001.09 python alternative. looks like you're quite the only one 👍

**Comment by sebastienrousseau** [comment]
@patroqueeet yep there's definitely a gap in the market and lots of other formats I would like to support. @patroqueeet let me know if you have any questions or any issues in your testing. Thanks
