### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by thegreengiant27** [sebastienrousseau/pain001#39]
I'm getting an error when I try to use the module using python 3.10.

Trying py -m pain001:

Traceback (most recent call last):
  File "C:\[...]\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\[...]\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\[...]\AppData\Local\Programs\Python\Python310\lib\site-packages\pain001\__main__.py", line 32, in <module>
    from pain001.constants.constants import valid_xml_types
ModuleNotFoundError: No module named 'pain001.constants'

And trying to use it in a file as per the snippet on the main page:
ImportError: cannot import name 'main' from 'pain001' (C:\[...]\AppData\Local\Programs\Python\Python310\lib\site-packages\pain001\__init__.py)

**Comment by sebastienrousseau** [comment]
@thegreengiant27 

Sorry to hear that you have encountered some issues.

1) Let's check the Installation: 

-  First, ensure that you've installed the package correctly. If you used pip, you might want to reinstall it:

```shell
pip uninstall pain001
pip install pain001
```

Let me know if this helps.

2) Let's verify the module structure:

Please try to navigate to the installation directory (as indicated in the error message, something like C:[...]\AppData\Local\Programs\Python\Python310\lib\site-packages\pain001) and check if the folder constants exists inside the pain001 directory. 

I will look on my side to reproduce this on Windows to identify what is the issue.

Thanks for taking the time to report your issue.

Best regards,
Sebastien

**Comment by sebastienrousseau** [comment]
@thegreengiant27 this should be fixed now in v0.0.25
