### ISSUE TITLE
ImportError: cannot import name 'main' from 'pain001'

### ISSUE THREAD

**Issue by MathMan112** [sebastienrousseau/pain001#44]
Upon attempting to use the library, the following error appears.

`ImportError: cannot import name 'main' from 'pain001' (C:\Users\User\anaconda3\Lib\site-packages\pain001\__init__.py)`

on `from pain001 import main`. What to do?

```

**Comment by warreee** [comment]
@MathMan112 I have the same issue, I fixed it with:
```python
from pain001.__main__ import main`
```

**Comment by sebastienrousseau** [comment]
@MathMan112 this should be fixed now in v0.0.25
