### ISSUE TITLE
Not all files are installed when installing with pip

### ISSUE THREAD

**Issue by warreee** [sebastienrousseau/pain001#46]
After you do a pip install you will get the following:
<img width="294" alt="Screenshot 2024-05-11 at 08 53 16" src="https://github.com/sebastienrousseau/pain001/assets/4020491/f1e1be21-2bf2-42f6-abb9-a489962253fd">

Not all files are installed which causes import errors.
I currently fixed by cloning the repo.

**Comment by sebastienrousseau** [comment]
@warreee this should be fixed now in v0.0.25
